export const SHOW_BILL_LIST_ONLINE ='SHOW_BILL_LIST_ONLINE';
export const SHOW_BILL_LIST_ONLINE_SUCCESS ='SHOW_BILL_LIST_ONLINE_SUCCESS';
export const SHOW_BILL_LIST_ONLINE_FAIL ='SHOW_BILL_LIST_ONLINE_FAIL';
