export const SHOW_PRODUCT_BILL_ONLINE ='SHOW_PRODUCT_BILL_ONLINE';
export const SHOW_PRODUCT_BILL_ONLINE_SUCCESS ='SHOW_PRODUCT_BILL_ONLINE_SUCCESS';
export const SHOW_PRODUCT_BILL_ONLINE_FAIL ='SHOW_PRODUCT_BILL_ONLINE_FAIL';
