export const SHOW_PRODUCT ='SHOW_PRODUCT';
export const SHOW_PRODUCT_SUCCESS ='SHOW_PRODUCT_SUCCESS';
export const SHOW_PRODUCT_FAIL ='SHOW_PRODUCT_FAIL';

export const ADD_PRODUCT ='ADD_PRODUCT';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const OPEN_FORM ='OPEN_FORM';