export const SHOW_BILL_LIST_OFF ='SHOW_BILL_LIST_OFF';
export const SHOW_BILL_LIST_OFF_SUCCESS ='SHOW_BILL_LIST_OFF_SUCCESS';
export const SHOW_BILL_LIST_OFF_FAIL ='SHOW_BILL_LIST_OFF_FAIL';

export const DALETE_BILL_OFF ='DALETE_BILL_OFF';

export const EDIT_BILL_OFF ='EDIT_BILL_OFF';
