export const SHOW_PRODUCT_BILL_OFF ='SHOW_PRODUCT_BILL_OFF';
export const SHOW_PRODUCT_BILL_OFF_SUCCESS ='SHOW_PRODUCT_BILL_OFF_SUCCESS';
export const SHOW_PRODUCT_BILL_OFF_FAIL ='SHOW_PRODUCT_BILL_OFF_FAIL';

export const EDIT_PRODUCT ='EDIT_PRODUCT';

export const BILL_PRODUCT_SEARCH ='BILL_PRODUCT_SEARCH';

export const BILL_PRODUCT_PAGINATION ='BILL_PRODUCT_PAGINATION';