export const SHOW_PRODUCT_SELL ='SHOW_PRODUCT_SELL';

export const SHOW_PRODUCT_SELL_SUCCESS ='SHOW_PRODUCT_SELL_SUCCESS';

export const OPEN_FORM ='OPEN_FORM'; 

export const ADD_PRODUCT_SELL ='ADD_PRODUCT_SELL';

export const DELETE_PRODUCT_SELL ='DELETE_PRODUCT_SELL';

export const FORM_EDIT = 'FORM_EDIT'; 

export const EDIT_PRODUCT_SELL = 'EDIT_PRODUCT_SELL'; 