export const SHOW_PRODUCT_QUANTITY ='SHOW_PRODUCT_QUANTITY';
export const SHOW_PRODUCT_QUANTITY_SUCCESS ='SHOW_PRODUCT_QUANTITY_SUCCESS';
export const SHOW_PRODUCT_QUANTITY_FAIL ='SHOW_PRODUCT_QUANTITY_FAIL';
