export const SHOW_BRANCH ='SHOW_BRANCH';
export const SHOW_BRANCH_SUCCESS ='SHOW_BRANCH_SUCCESS';
export const SHOW_BRANCH_FAIL ='SHOW_BRANCH_FAIL';

export const ADD_BRANCH ='ADD_BRANCH';

export const EDIT_BRANCH = 'EDIT_BRANCH';

export const OPEN_FORM ='OPEN_FORM';