export const SHOW_BILL_LIST_ONLINE ='SHOW_BILL_LIST_ONLINE';
export const SHOW_BILL_LIST_ONLINE_SUCCESS ='SHOW_BILL_LIST_ONLINE_SUCCESS';
export const SHOW_BILL_LIST_ONLINE_FAIL ='SHOW_BILL_LIST_ONLINE_FAIL';

export const DALETE_BILL_ONLINE ='DALETE_BILL_ONLINE';

export const EDIT_BILL_ONLINE ='EDIT_BILL_ONLINE';
