export const SHOW_PRODUCT_BILL ='SHOW_PRODUCT_BILL';
export const SHOW_PRODUCT_BILL_SUCCESS ='SHOW_PRODUCT_BILL_SUCCESS';
export const SHOW_PRODUCT_BILL_FAIL ='SHOW_PRODUCT_BILL_FAIL';

export const EDIT_PRODUCT ='EDIT_PRODUCT';

export const BILL_PRODUCT_SEARCH ='BILL_PRODUCT_SEARCH';

export const BILL_PRODUCT_PAGINATION ='BILL_PRODUCT_PAGINATION';