export const SHOW_PRODUCT_BILL_OFF ='SHOW_PRODUCT_BILL_OFF';
export const SHOW_PRODUCT_BILL_OFF_SUCCESS ='SHOW_PRODUCT_BILL_OFF_SUCCESS';
export const SHOW_PRODUCT_BILL_OFF_FAIL ='SHOW_PRODUCT_BILL_OFF_FAIL';
