
export const  FETCH_PRODUCT_BILL = 'FETCH_PRODUCT_BILL';
export const  FETCH_PRODUCT_BILL_SUCCESS = 'FETCH_PRODUCT_BILL_SUCCESS';
export const  FETCH_PRODUCT_BILL_FAILED = 'FETCH_PRODUCT_BILL_FAILED';

export const  COMPLETE_PRODUCT_BILL = 'COMPLETE_PRODUCT_BILL';

export const  DELETE_PRODUCT_BILL = 'DELETE_PRODUCT_BILL';

export const TIME_BILL = 'TIME_BILL';