export const  FETCH_PRODUCT_CART = 'FETCH_PRODUCT_CART';
export const  FETCH_PRODUCT_CART_SUCCESS = 'FETCH_PRODUCT_CART_SUCCESS';
export const  FETCH_PRODUCT_CART_FAILED = 'FETCH_PRODUCT_CART_FAILED';

export const  ADD_TO_CART_POST = 'ADD_TO_CART_POST';
export const  ADD_TO_CART_PUT = 'ADD_TO_CART_PUT';

export const  UPDATE_TO_CART = 'UPDATE_TO_CART';

export const  DELETE_TO_CART = 'DELETE_TO_CART';

export const  COMPLETE_DELETE_CART = 'COMPLETE_DELETE_CART';